# This file was generated by GoReleaser. DO NOT EDIT.
cask "d9s" do
  version "0.0.1-rc2"

  on_macos do
    on_intel do
      sha256 "726463eb6dfd80cc6e2358397d9f0032cb406de72f633827f168e7c92c9a729a"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
    on_arm do
      sha256 "7c775fc277347345ca7ac4ff4f73ff0af7326f284f20f5e34e72cc288c94feb2"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc70e7a1d3a052b47f73242c26006b71db228420a9b920fdfac95aa343d120cc"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_linux_amd64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
    on_arm do
      sha256 "9252ec5b15ef494414b2340354ad59052dc5fb7a71a0f12a8ac0da2240d971bc"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
  end

  name "d9s"
  desc "A k9s-style terminal UI for PostgreSQL, ClickHouse, and Redis"
  homepage "https://github.com/lergor11/d9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "d9s"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/d9s"]
    end
  end

  # No zap stanza required

end
