# This file was generated by GoReleaser. DO NOT EDIT.
cask "d9s" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "710a15a37397c6ccf3493a9a5e2459bf77bc368cbb358ab2acb922d34f82d60d"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
    on_intel do
      sha256 "b39385805805c4148de2927c6f96814e9d1783420ba3ffc57f4fd740a008d23f"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
  end
  on_linux do
    on_arm do
      sha256 "cce03a1170c0927abfa45e7e0f6d9fe6443e19e7caed86cd1005ad35105feef5"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
    on_intel do
      sha256 "c1f07221dfebbee5a082f21742f873e17ac2c05fa306eeb8003f3f892c494d2e"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_linux_amd64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
  end

  name "d9s"
  desc "A k9s-style terminal UI for PostgreSQL, ClickHouse, and Redis"
  homepage "https://github.com/lergor11/d9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "d9s"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/d9s"]
    end
  end

  # No zap stanza required
end
