# This file was generated by GoReleaser. DO NOT EDIT.
cask "d9s" do
  version "0.0.1-rc3"

  on_macos do
    on_intel do
      sha256 "37cca5f3e3517fdeb7ba1ad366222d83ea819bf3d3a032001bf19eb2149f934b"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
    on_arm do
      sha256 "96117174c3abf3b461a24ed6b7e7503f8046128f9cf6488b67f7e481b3ed7d7c"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
  end

  on_linux do
    on_intel do
      sha256 "18a2e77ca6fd9e41d06d8cf3cbfa76bede23d58f79b6097ebf09a83805551103"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_linux_amd64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
    on_arm do
      sha256 "e375dcba0f7b1ff3327310a17944a4d366bc1b26809f6731e3dd5abca2cc2724"
      url "https://github.com/lergor11/d9s/releases/download/v#{version}/d9s_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lergor11/d9s/"
    end
  end

  name "d9s"
  desc "A k9s-style terminal UI for PostgreSQL, ClickHouse, and Redis"
  homepage "https://github.com/lergor11/d9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "d9s"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/d9s"]
    end
  end

  # No zap stanza required

end
